export const JOIN_CHAT_REQUEST: 'JOIN_CHAT_REQUEST' = 'JOIN_CHAT_REQUEST';
export const JOIN_CHAT_SUCCESS: 'JOIN_CHAT_SUCCESS' = 'JOIN_CHAT_SUCCESS';
export const JOIN_CHAT_FAILED: 'JOIN_CHAT_FAILED' = 'JOIN_CHAT_FAILED';