export const STATUS_DATA: 'STATUS/DATA' = 'STATUS/DATA';
export const DIRECTIONS_DATA: 'DIRECTIONS/DATA' = 'DIRECTIONS/DATA';
export const EXECUTOR_DATA: 'EXECUTOR/DATA' = 'EXECUTOR/DATA';
export const CREATOR_DATA: 'CREATOR/DATA' = 'CREATOR/DATA';
